# Docker Compose for running on stage and production

version: "3.8"

name: mss

services:
  mss-backend:
    container_name: mss-backend
    image: mss-backend:latest
    build:
      context: ./backend
    restart: always
    ports:
      - ${BACKEND_PUBLISH_PORT}:80

  mss-notifier:
    container_name: mss-notifier
    image: mss-notifier:latest
    build:
      context: ./notifier
    restart: always
    ports:
      - ${NOTIFIER_PUBLISH_PORT}:80

  mss-telegram:
    container_name: mss-telegram
    image: mss-telegram:latest
    build:
      context: ./telegram
    restart: always

  mss-scrapper:
    container_name: mss-scrapper
    image: mss-scrapper:latest
    build:
      context: ./scrapper
    restart: always

  mss-frontend:
    container_name: mss-frontend
    image: mss-frontend:latest
    build:
      context: ./frontend
      args:
        GITHUB_RUN_NUMBER_ARG: ${GITHUB_RUN_NUMBER}
    restart: always
    volumes:
      - ${FRONTEND_PUBLISH_PATH}:/usr/src/app/mount
