version: "3.8"

name: mss

volumes:
  mss-keycloak-postgres:
    name: mss-keycloak-postgres

services:
  mss-backend: 
    container_name: mss-backend
    image: mss-backend:latest
    build:
      context: ./backend
    restart: always
    ports:
      - 127.0.0.1:${BACKEND_PUBLISH_PORT}:80

  mss-notifier:
    container_name: mss-notifier
    image: mss-notifier:latest
    build:
      context: ./notifier
    restart: always
    ports:
      - 127.0.0.1:${NOTIFIER_PUBLISH_PORT}:80

  mss-telegram:
    container_name: mss-telegram
    image: mss-telegram:latest
    build:
      context: ./telegram
    restart: always

  mss-scrapper:
    container_name: mss-scrapper
    image: mss-scrapper:latest
    build:
      context: ./scrapper
    restart: always

  mss-frontend:
    container_name: mss-frontend
    image: mss-frontend:latest
    build:
      context: ./frontend
      args:
        GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}
    restart: always
    volumes:
      - ${FRONTEND_PUBLISH_PATH}:/usr/src/app/mount

  mss-keycloak:
    container_name: mss-keycloak
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://mss-keycloak-postgres:5432/${KEYCLOAK_POSTGRES_DB}
      KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HOSTNAME_PORT: ${KEYCLOAK_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTP_ENABLED: "true"
      KC_LOG_LEVEL: warn
      KC_PROXY: edge
    ports:
      - 127.0.0.1:${KEYCLOAK_PUBLISH_PORT}:8443
    depends_on:
      - mss-keycloak-postgres
    volumes:
      - ./keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ${KEYCLOAK_PUBLIC_CERT_FILE_PATH}:/opt/keycloak/conf/public.crt:ro
      - ${KEYCLOAK_PRIVATE_KEY_FILE_PATH}:/opt/keycloak/conf/private.key:ro
    command:
      - start
      - --https-certificate-file=/opt/keycloak/conf/public.crt
      - --https-certificate-key-file=/opt/keycloak/conf/private.key

  mss-keycloak-postgres:
    container_name: mss-keycloak-postgres
    image: postgres:16-alpine
    restart: on-failure
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    volumes:
      - mss-keycloak-postgres:/var/lib/postgresql/data
      - ./keycloak/postgresql.conf:/etc/postgresql/postgresql.conf
