{
 "title": "MSS Backend Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Rate: RMP",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"4.*\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{code=~\"5.*\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Processing time by requests (ms)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{code=~\"2.*\"}[5m]) / rate(http_request_duration_seconds_count{code=~\"2.*\"}[5m]) * 1000",
     "legendFormat": "Average {{route}}"
    }
   ]
  }
 ]
}