version: "3.8"

name: mss-prometheus

volumes:
  mss-prometheus-data:
    name: mss-prometheus-data
  mss-grafana-data:
    name: mss-grafana-data
  mss-grafana-home:
    name: mss-grafana-home

services:
  mss-prometheus:
    container_name: mss-prometheus
    image: prom/prometheus
    restart: on-failure
    ports:
      - 127.0.0.1:6804:9090
    volumes:
      - ./monprometheus.yml:/etc/prometheus/prometheus.yml
      - mss-prometheus-data:/prometheus

  mss-grafana:
    container_name: mss-grafana
    image: grafana/grafana
    restart: on-failure
    depends_on:
      - mss-prometheus
    ports:
      - 127.0.0.1:6805:3000
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/node-dashboard.json:/etc/grafana/provisioning/dashboards/node-dashboard.json
      - mss-grafana-data:/var/lib/grafana
      - mss-grafana-home:/usr/share/grafana
