name: Pipeline for only MASTER

on:
  pull_request:
    branches: [ master ]
    types:
      - closed

  workflow_dispatch:

jobs:
  
  copy:
    name: Remove old project folder and copy to its place new one
    runs-on: self-hosted

    steps:
      - name: Clear old workdir
        run: rm -rf $GITHUB_WORKSPACE/*
      - uses: actions/checkout@v2
      - name: Move old mss dir
        run: |
          cd ~ &&
          rm -rf mss_old/ &&
          [ -d mss ] &&
          mv mss mss_old &&
          figlet "Moved old ~/mss" ||
          echo "No old folder so not deleting it"
      - name: Copy fresh project into ~/mss folder
        run: cd .. && cp -r mss ~/mss
      - name: Copy configs to each folder
        run: |
          cp ~/MSS_CONFIGS/notifier-and-logger.config.json ~/mss/notifier/ &&
          cp ~/MSS_CONFIGS/ci.config.json ~/mss/cicd/ &&
          cp ~/MSS_CONFIGS/scrapper.config.json ~/mss/scrapper/ &&
          cp ~/MSS_CONFIGS/backend.config.json ~/mss/backend/ &&
          cp ~/MSS_CONFIGS/telegram-bot.config.json ~/mss/telegram/ &&
          mv ~/mss/telegram/cats ~/mss/telegram/cats_old &&
          ln -s ~/MSS_CONFIGS/cats ~/mss/telegram/cats

  notifier:
    name: Folder for NOTIFIER
    runs-on: self-hosted
    needs: copy

    steps:
      - name: npm install
        run: cd ~/mss/notifier/ && npm i --progress=false --only=prod
      - name: Delete old PM2 instance
        run: |
          pm2 delete notifier-and-logger 2> /dev/null &&
          echo "Process <notifier-and-logger> exited successfully" ||
          echo "Process <notifier-and-logger> did not run on PM2"
      - name: Delete previous PM2 logs
        run: cd ~/.pm2/logs/ && rm -rf notifier-and-logger-*
      - name: Start new PM2 instance
        run: cd ~/mss/notifier/ && pm2 start notifier-and-logger.js

  cicd:
    name: Folder for CI/CD
    runs-on: self-hosted
    needs: notifier

    steps:
      - name: npm install
        run: cd ~/mss/cicd/ && npm i --progress=false --only=prod

  scrapper:
    name: Folder for SCRAPPER
    runs-on: self-hosted
    needs: notifier

    steps:
      - name: npm install
        run: cd ~/mss/scrapper/ && npm i --progress=false --only=prod

  backend:
    name: Folder for BACKEND
    runs-on: self-hosted
    needs: notifier

    steps:
      - name: npm install
        run: cd ~/mss/backend/ && npm i --progress=false --only=prod
      - name: Delete old PM2 instance
        run: |
          pm2 delete backend-server 2> /dev/null &&
          echo "Process <backend-server> exited successfully" ||
          echo "Process <backend-server> did not run on PM2"
      - name: Delete previous PM2 logs
        run: cd ~/.pm2/logs/ && rm -rf backend-server-*
      - name: Start new PM2 instance
        run: cd ~/mss/backend/ && pm2 start backend-server.js

  telegram:
    name: Folder for TELEGRAM
    runs-on: self-hosted
    needs: notifier

    steps:
      - name: npm install
        run: cd ~/mss/telegram/ && npm i --progress=false --only=prod
      - name: Delete old PM2 instance
        run: |
          pm2 delete telegram-bot 2> /dev/null &&
          echo "Process <telegram-bot> exited successfully" ||
          echo "Process <telegram-bot> did not run on PM2"
      - name: Delete previous PM2 logs
        run: cd ~/.pm2/logs/ && rm -rf telegram-bot-*
      - name: Start new PM2 instance
        run: cd ~/mss/telegram/ && pm2 start telegram-bot.js

  frontend:
    name: Folder for FRONTEND
    runs-on: self-hosted
    needs:
      - cicd
      - scrapper
      - backend
      - telegram

    steps:
      - name: npm install
        run: cd ~/mss/frontend/ && npm i --progress=false --only=prod
      - name: npm run build
        run: cd ~/mss/frontend/ && npm run build

  redoc:
    name: Generate Redoc
    runs-on: self-hosted
    needs: frontend

    steps:
      - name: Generate file
        run: cd ~/mss/frontend/ && npm exec -- redoc-cli bundle public/docs/api/v1.1.yml -o dist/docs/api/redoc.html

  final:
    name: Showing and sending final logs
    runs-on: self-hosted
    needs: redoc

    steps:
      - name: Show PM2 processes list
        run: pm2 list
      - name: Send notification in Telegram
        run: |
          [ -f ~/mss/cicd/ci-notify.js ] &&
          node ~/mss/cicd/ci-notify.js "Done merge into master | Actor: $GITHUB_ACTOR" ||
          echo "No CI notifier (Done merge into master | Actor: $GITHUB_ACTOR)"
