name: Pipeline for only MASTER

on:
  pull_request:
    branches: [ master ]
    types:
      - closed

  workflow_dispatch:

jobs:
  
  copy:
    name: Remove old project folder and copy to its place new one
    runs-on: self-hosted

    steps:
      - name: Clear old workdir
        run: rm -rf $GITHUB_WORKSPACE/*
      - uses: actions/checkout@v2
      - name: Move old mss dir
        run: |
          cd ~ &&
          rm -rf mss_old/ &&
          [ -d mss ] &&
          mv mss mss_old &&
          figlet "Moved old ~/mss" ||
          echo "No old folder so not deleting it"
      - name: Copy fresh project into ~/mss folder
        run: cd .. && cp -r mss ~/mss
      - name: Copy configs to each folder
        run: |
          cp ~/MSS_CONFIGS/notifier-and-logger.config.json ~/mss/notifier/ &&
          cp ~/MSS_CONFIGS/ci.config.json ~/mss/cicd/ &&
          cp ~/MSS_CONFIGS/scrapper.config.json ~/mss/scrapper/ &&
          cp ~/MSS_CONFIGS/backend.config.json ~/mss/backend/

  notifier:
    name: Folder for NOTIFIER
    runs-on: self-hosted
    needs: copy

    steps:
      - name: npm install
        run: cd ~/mss/notifier/ && npm install --progress=false
      - name: Delete old PM2 instance
        run: |
          pm2 delete notifier-and-logger 2> /dev/null &&
          echo "Process <notifier-and-logger> exited successfully" ||
          echo "Process <notifier-and-logger> did not run on PM2"
      - name: Delete previous PM2 logs
        run: cd ~/.pm2/logs/ && rm notifier-and-logger-*
      - name: Start new PM2 instance
        run: cd ~/mss/notifier/ && pm2 start notifier-and-logger.js

  cicd:
    name: Folder for CI/CD
    runs-on: self-hosted
    needs: [ copy, notifier ]

    steps:
      - name: npm install
        run: cd ~/mss/cicd/ && npm install --progress=false

  scrapper:
    name: Folder for SCRAPPER
    runs-on: self-hosted
    needs: [ copy, notifier ]

    steps:
      - name: npm install
        run: cd ~/mss/scrapper/ && npm install --progress=false

  backend:
    name: Folder for BACKEND
    runs-on: self-hosted
    needs: [ copy, notifier ]

    steps:
      - name: npm install
        run: cd ~/mss/backend/ && npm install --progress=false
      - name: Delete old PM2 instance
        run: |
          pm2 delete backend-server 2> /dev/null &&
          echo "Process <backend-server> exited successfully" ||
          echo "Process <backend-server> did not run on PM2"
      - name: Delete previous PM2 logs
        run: cd ~/.pm2/logs/ && rm backend-server-*
      - name: Start new PM2 instance
        run: cd ~/mss/backend/ && pm2 start backend-server.js

  frontend:
    name: Folder for FRONTEND
    runs-on: self-hosted
    needs: [ copy, notifier ]

    steps:
      - name: npm install
        run: cd ~/mss/frontend/ && npm install --progress=false
      - name: npm run build
        run: cd ~/mss/frontend/ && npm run build

  final:
    name: Showing final logs
    runs-on: self-hosted
    needs:
      - copy
      - notifier
      - cicd
      - scrapper
      - backend
      - frontend

    steps:
      - name: Show pm2 list
        run: pm2 list
    