name: Notify on push and merge

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
  pull_request:
    types:
      - closed
    branches:
      - '*'
      - '*/*'
      - '**'

  workflow_dispatch:

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Actual notify step
        run: |
          [ -f ~/mss/cicd/ci-notify.js ] &&
          node ~/mss/cicd/ci-notify.js "Actor: $GITHUB_ACTOR | Brahch: ${GITHUB_REF#refs/heads/} | Event: $GITHUB_EVENT_NAME" ||
          echo "No CI notifier (Actor: $GITHUB_ACTOR | Brahch: ${GITHUB_REF#refs/heads/} | Event: $GITHUB_EVENT_NAME)"
