name: Notify on push

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"

  workflow_dispatch:

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Send notification
        env:
          CONFIGS_LOCATION_BASE: ${{ secrets.CONFIGS_LOCATION_BASE }}
        run: |
          source $CONFIGS_LOCATION_BASE/docker.env;
          curl http://127.0.0.1:$NOTIFIER_PUBLISH_PORT -d "{\"error\":false,\"args\":[\"User $GITHUB_ACTOR pushed to branch ${GITHUB_REF#refs/heads/}\"],\"tag\":\"ci\"}" ||
          echo "Error while sending notification"
