name: Notify on push and merge

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!master'

  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'

  workflow_dispatch:

jobs:
  notify:
    runs-on: self-hosted
    steps:
      - name: Actual notify step
        run: |
          [ -f ~/mss/cicd/ci-notify.js ] &&
          node ~/mss/cicd/ci-notify.js "Actor: $GITHUB_ACTOR" "Branch: ${GITHUB_REF#refs/heads/}" "Head ref: $GITHUB_HEAD_REF" "Base ref: $GITHUB_BASE_REF" "Event: $GITHUB_EVENT_NAME" ||
          printf "No CI notifier\n\tActor: $GITHUB_ACTOR\n\tBranch: ${GITHUB_REF#refs/heads/}\n\tHead ref: $GITHUB_HEAD_REF\n\tBase ref: $GITHUB_BASE_REF\n\tEvent: $GITHUB_EVENT_NAME\n"
